# golangci-lint v2 configuration
version: "2"

run:
  timeout: 5m

formatters:
  settings:
    gofumpt:
      module-path: github.com/dexfra-fun/x402-go
      extra-rules: true

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - copyloopvar
    - cyclop
    - dupl
    - durationcheck
    - errname
    - errorlint
    - exhaustive
    - fatcontext
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goprintffuncname
    - gosec
    - intrange
    - makezero
    - mirror
    - mnd
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - nonamedreturns
    - perfsprint
    - predeclared
    - reassign
    - revive
    - rowserrcheck
    - sloglint
    - sqlclosecheck
    - testableexamples
    - testifylint
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign
    - whitespace

  settings:
    revive:
      # Maximum number of open files at the same time.
      max-open-files: 2048
      # Sets the default severity.
      severity: warning
      # Enable all available rules.
      enable-all-rules: true
      # Sets the default failure confidence.
      confidence: 0.8
      rules:
        # Disable overly strict rules for this project
        - name: add-constant
          disabled: true
        - name: argument-limit
          disabled: true
        - name: banned-characters
          disabled: true
        - name: cognitive-complexity
          severity: warning
          disabled: false
          arguments: [25]
        - name: comment-spacings
          disabled: true
        - name: comments-density
          disabled: true
        - name: cyclomatic
          severity: warning
          disabled: false
          arguments: [10]
        - name: file-header
          disabled: true
        - name: file-length-limit
          disabled: true
        - name: filename-format
          disabled: true
        - name: flag-parameter
          disabled: true
        - name: function-length
          severity: warning
          disabled: false
          arguments: [60, 0]
        - name: function-result-limit
          disabled: true
        - name: line-length-limit
          disabled: true
        - name: max-control-nesting
          disabled: true
        - name: max-public-structs
          disabled: true
        - name: package-comments
          disabled: true
        - name: unused-parameter
          severity: warning
          disabled: false
          arguments:
            - allow-regex: "^_"
        - name: unused-receiver
          severity: warning
          disabled: false
          arguments:
            - allow-regex: "^_"
        - name: var-naming
          severity: warning
          disabled: false
          arguments:
            - ["ID", "API", "URL", "HTTP", "JSON", "XML", "HTML"]
            - []
