// Code generated by "enumer -type=FacilitatorID -json -text -yaml -sql -transform=snake"; DO NOT EDIT.

package x402

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"strings"
)

const _FacilitatorIDName = "facilitator_id_unknownfacilitator_id_pay_aifacilitator_id_coinbasefacilitator_id_open_x402facilitator_id_aurra_cloudfacilitator_id_code_nutfacilitator_id_corbitsfacilitator_id_daydreamsfacilitator_id_dexterfacilitator_id_ultravioleta_dao"

var _FacilitatorIDIndex = [...]uint8{0, 22, 43, 66, 90, 116, 139, 161, 185, 206, 237}

const _FacilitatorIDLowerName = "facilitator_id_unknownfacilitator_id_pay_aifacilitator_id_coinbasefacilitator_id_open_x402facilitator_id_aurra_cloudfacilitator_id_code_nutfacilitator_id_corbitsfacilitator_id_daydreamsfacilitator_id_dexterfacilitator_id_ultravioleta_dao"

func (i FacilitatorID) String() string {
	if i < 0 || i >= FacilitatorID(len(_FacilitatorIDIndex)-1) {
		return fmt.Sprintf("FacilitatorID(%d)", i)
	}
	return _FacilitatorIDName[_FacilitatorIDIndex[i]:_FacilitatorIDIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _FacilitatorIDNoOp() {
	var x [1]struct{}
	_ = x[FacilitatorIDUnknown-(0)]
	_ = x[FacilitatorIDPayAI-(1)]
	_ = x[FacilitatorIDCoinbase-(2)]
	_ = x[FacilitatorIDOpenX402-(3)]
	_ = x[FacilitatorIDAurraCloud-(4)]
	_ = x[FacilitatorIDCodeNut-(5)]
	_ = x[FacilitatorIDCorbits-(6)]
	_ = x[FacilitatorIDDaydreams-(7)]
	_ = x[FacilitatorIDDexter-(8)]
	_ = x[FacilitatorIDUltravioletaDAO-(9)]
}

var _FacilitatorIDValues = []FacilitatorID{FacilitatorIDUnknown, FacilitatorIDPayAI, FacilitatorIDCoinbase, FacilitatorIDOpenX402, FacilitatorIDAurraCloud, FacilitatorIDCodeNut, FacilitatorIDCorbits, FacilitatorIDDaydreams, FacilitatorIDDexter, FacilitatorIDUltravioletaDAO}

var _FacilitatorIDNameToValueMap = map[string]FacilitatorID{
	_FacilitatorIDName[0:22]:         FacilitatorIDUnknown,
	_FacilitatorIDLowerName[0:22]:    FacilitatorIDUnknown,
	_FacilitatorIDName[22:43]:        FacilitatorIDPayAI,
	_FacilitatorIDLowerName[22:43]:   FacilitatorIDPayAI,
	_FacilitatorIDName[43:66]:        FacilitatorIDCoinbase,
	_FacilitatorIDLowerName[43:66]:   FacilitatorIDCoinbase,
	_FacilitatorIDName[66:90]:        FacilitatorIDOpenX402,
	_FacilitatorIDLowerName[66:90]:   FacilitatorIDOpenX402,
	_FacilitatorIDName[90:116]:       FacilitatorIDAurraCloud,
	_FacilitatorIDLowerName[90:116]:  FacilitatorIDAurraCloud,
	_FacilitatorIDName[116:139]:      FacilitatorIDCodeNut,
	_FacilitatorIDLowerName[116:139]: FacilitatorIDCodeNut,
	_FacilitatorIDName[139:161]:      FacilitatorIDCorbits,
	_FacilitatorIDLowerName[139:161]: FacilitatorIDCorbits,
	_FacilitatorIDName[161:185]:      FacilitatorIDDaydreams,
	_FacilitatorIDLowerName[161:185]: FacilitatorIDDaydreams,
	_FacilitatorIDName[185:206]:      FacilitatorIDDexter,
	_FacilitatorIDLowerName[185:206]: FacilitatorIDDexter,
	_FacilitatorIDName[206:237]:      FacilitatorIDUltravioletaDAO,
	_FacilitatorIDLowerName[206:237]: FacilitatorIDUltravioletaDAO,
}

var _FacilitatorIDNames = []string{
	_FacilitatorIDName[0:22],
	_FacilitatorIDName[22:43],
	_FacilitatorIDName[43:66],
	_FacilitatorIDName[66:90],
	_FacilitatorIDName[90:116],
	_FacilitatorIDName[116:139],
	_FacilitatorIDName[139:161],
	_FacilitatorIDName[161:185],
	_FacilitatorIDName[185:206],
	_FacilitatorIDName[206:237],
}

// FacilitatorIDString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func FacilitatorIDString(s string) (FacilitatorID, error) {
	if val, ok := _FacilitatorIDNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _FacilitatorIDNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to FacilitatorID values", s)
}

// FacilitatorIDValues returns all values of the enum
func FacilitatorIDValues() []FacilitatorID {
	return _FacilitatorIDValues
}

// FacilitatorIDStrings returns a slice of all String values of the enum
func FacilitatorIDStrings() []string {
	strs := make([]string, len(_FacilitatorIDNames))
	copy(strs, _FacilitatorIDNames)
	return strs
}

// IsAFacilitatorID returns "true" if the value is listed in the enum definition. "false" otherwise
func (i FacilitatorID) IsAFacilitatorID() bool {
	for _, v := range _FacilitatorIDValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for FacilitatorID
func (i FacilitatorID) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for FacilitatorID
func (i *FacilitatorID) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("FacilitatorID should be a string, got %s", data)
	}

	var err error
	*i, err = FacilitatorIDString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for FacilitatorID
func (i FacilitatorID) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for FacilitatorID
func (i *FacilitatorID) UnmarshalText(text []byte) error {
	var err error
	*i, err = FacilitatorIDString(string(text))
	return err
}

// MarshalYAML implements a YAML Marshaler for FacilitatorID
func (i FacilitatorID) MarshalYAML() (interface{}, error) {
	return i.String(), nil
}

// UnmarshalYAML implements a YAML Unmarshaler for FacilitatorID
func (i *FacilitatorID) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var s string
	if err := unmarshal(&s); err != nil {
		return err
	}

	var err error
	*i, err = FacilitatorIDString(s)
	return err
}

func (i FacilitatorID) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *FacilitatorID) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	var str string
	switch v := value.(type) {
	case []byte:
		str = string(v)
	case string:
		str = v
	case fmt.Stringer:
		str = v.String()
	default:
		return fmt.Errorf("invalid value of FacilitatorID: %[1]T(%[1]v)", value)
	}

	val, err := FacilitatorIDString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}
